name: Markdown Linting

on: [push, pull_request]

jobs:
  run-as-action:
    name: Run Markdown Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check all Markdown files except SUMMARY.md
        uses: ./
        with:
          args: '**/*.md'
          ignore: './src/SUMMARY.md'
          config: './lint/config/default.yml'

      # Summary has MD025 and MD041 turned off due to how mdbook expects the file SUMMARY.md
      - name: Check SUMMARY.md
        uses: ./
        with:
          args: './src/SUMMARY.md'
          config: './lint/config/summary.yml'
